GET http://localhost:4500/users


###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username":"Narutos",
    "email":"Narutos",
    "password":"ninetailfox",
    "Roles":"Admin"

}


###
DELETE http://localhost:4500/users


###
PATCH http://localhost:4500/users